/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [],
    theme: {
        extend: {
            fontFamily: {
                taiwan: ['Noto Serif CJK TC', 'sans-serif'],
                nihon: ['Noto Serif CJK JP', 'sans-serif'],
            },
        },
    },
    safelist: [
        "aspect-square",
        "bg-blue-500",
        "bg-gray-100",
        "bg-gray-300",
        "bg-green-500",
        "bg-red-500",
        "bg-white",
        "border",
        "border-b",
        "border-gray-200",
        "flex",
        "font-bold",
        "font-nihon",
        "font-taiwan",
        "h-6",
        "inline-flex",
        "items-center",
        "justify-between",
        "mb-6",
        "min-w-full",
        "mx-auto",
        "p-2",
        "p-6",
        "pb-3",
        "px-2",
        "px-4",
        "py-1",
        "py-2",
        "rounded",
        "rounded-full",
        "rounded-lg",
        "rounded-md",
        "shadow-lg",
        "space-x-4",
        "text-3xl",
        "text-gray-700",
        "text-left",
        "text-white",
        "w-full",
        "whitespace-nowrap",
    ],
    plugins: [],
}

