services:
  postgres:
    image: "postgres:15.7-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    entrypoint: [ "bash", "-c" ]
    command: [ "alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --reload" ]
    depends_on:
      - postgres
