"""Add difficult kanji

Revision ID: 2ccfe06bbc4d
Revises: 67e942785512
Create Date: 2024-08-11 12:26:54.518227

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.orm import Session

from migrations.seed_loader import insert_kanji

# revision identifiers, used by Alembic.
revision: str = "2ccfe06bbc4d"
down_revision: Union[str, None] = "67e942785512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as session:
        insert_kanji(session, "./migrations/seeds/difficult_kanji.csv")
        session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
