"""Remove foreign key constraints between kanji and thy_name

Revision ID: 67e942785512
Revises: dc2325b33b3f
Create Date: 2024-08-09 08:01:31.247687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67e942785512"
down_revision: Union[str, None] = "dc2325b33b3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("thy_name_kanji_id_fkey", "thy_name", type_="foreignkey")
    op.drop_column("thy_name", "kanji_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thy_name",
        sa.Column("kanji_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "thy_name_kanji_id_fkey", "thy_name", "kanji", ["kanji_id"], ["id"]
    )
    # ### end Alembic commands ###
