"""create initial tables

Revision ID: dc2325b33b3f
Revises:
Create Date: 2024-08-07 01:31:25.556234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from migrations.seed_loader import insert_kanji

# revision identifiers, used by Alembic.
revision: str = "dc2325b33b3f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kanji",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character", sa.String(length=1), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character"),
    )
    op.create_table(
        "thy_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("kanji_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kanji_id"],
            ["kanji.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as session:
        insert_kanji(session)
        session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thy_name")
    op.drop_table("kanji")
    # ### end Alembic commands ###
